export const ShopActionTypes = {
    ADD_SHOP_DATA: 'ADD_SHOP_DATA',
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_ERROR: 'FETCH_COLLECTION_ERROR',
};
